Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 10
  Enabled: true
  Severity: Convention
  Excluded:
  - src/scanner.cr