Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 10
  Enabled: false
  Severity: Convention
  Excluded:
    - src/lit/scanner.cr
Documentation/DocumentationAdmonition:
  Enabled: false
Naming/BlockParameterName:
  Enabled: false
Lint/NotNil:
  Enabled: false
