Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 10
  Enabled: false
  Severity: Convention
  Excluded:
    - src/lit/scanner.cr
