module Lit
  KEYWORDS = {
    and:    TokenType::AND,
    break:  TokenType::BREAK,
    do:     TokenType::DO,
    else:   TokenType::ELSE,
    false:  TokenType::FALSE,
    fn:     TokenType::FN,
    if:     TokenType::IF,
    import: TokenType::IMPORT,
    is:     TokenType::EQUAL_EQUAL,
    var:    TokenType::VAR,
    let:    TokenType::LET,
    loop:   TokenType::LOOP,
    match:  TokenType::MATCH,
    next:   TokenType::NEXT,
    nil:    TokenType::NIL,
    or:     TokenType::OR,
    return: TokenType::RETURN,
    self:   TokenType::SELF,
    then:   TokenType::THEN,
    true:   TokenType::TRUE,
    type:   TokenType::TYPE,
    until:  TokenType::UNTIL,
    while:  TokenType::WHILE,
  }
end
