module Lit
  enum TokenType
    LEFT_PAREN; RIGHT_PAREN; LEFT_BRACKET; RIGHT_BRACKET; LEFT_BRACE; RIGHT_BRACE

    COMMA; DOT; COLON; NEWLINE

    # Math
    PLUS; MINUS; SLASH; STAR; STAR_STAR; PERCENT

    # Augmented assignment
    PLUS_EQUAL; MINUS_EQUAL; SLASH_EQUAL; STAR_EQUAL; PERCENT_EQUAL

    # Comparison
    EQUAL; EQUAL_EQUAL; GREATER; GREATER_EQUAL; LESS; LESS_EQUAL

    BAR; BANG; BANG_EQUAL; QUESTION
    PIPE_GREATER

    # Literals
    NUMBER; STRING; IDENTIFIER; STRING_INTERPOLATION; SYMBOL

    # Keywords
    AND; DO; ELSE; FALSE; FN; IF; VAR; LET; NIL; OR; PRINT; PRINTLN; RETURN; TRUE; TYPE; SELF; WHILE; UNTIL; LOOP; BREAK; NEXT; IMPORT

    EOF

    def keyword? : Bool
      self.in? KEYWORDS.values
    end
  end
end
