module Lit
  enum TokenType
    LEFT_PAREN; RIGHT_PAREN; LEFT_BRACKET; RIGHT_BRACKET; LEFT_BRACE; RIGHT_BRACE

    COMMA; DOT; SEMICOLON

    # Math
    PLUS; MINUS; SLASH; STAR; STAR_STAR

    EQUAL; EQUAL_EQUAL; GREATER; GREATER_EQUAL; LESS; LESS_EQUAL

    BAR; BAR_BAR; BANG; BANG_EQUAL
    PIPE_OPERATOR; ARROW

    # Literals
    NUMBER; STRING; IDENTIFIER

    # Keywords
    AND; ELSE; FALSE; FN; IF; LET; NIL; OR; PRINT; PUTS; RETURN; TRUE; WHILE

    EOF
  end
end
