#!/bin/bash

echo "require \"./spec/**\"" > run_tests.cr && \
crystal build run_tests.cr -D skip-integration && \
kcov --include-path=$(pwd)/src $(pwd)/coverage ./run_tests
google-chrome coverage/index.html